"""Add user stats fields

Revision ID: 6d8085c3a14c
Revises: 
Create Date: 2025-07-31 01:11:22.009966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8085c3a14c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_answers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('user_answers')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('correct_answers')

    # ### end Alembic commands ###
